import = [
    "%APPDATA%\\alacritty\\themes\\tokyo-night.yaml",
    # "~/.config/alacritty/themes/tokyo-night.yaml",
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.75
padding = { x = 10, y = 10 }
decorations = "Buttonless"
blur = true
option_as_alt = "Both"

[font]
normal = { family = "Mononoki Nerd Font", style = "Regular" }